### PR TITLE
Add CodeCov to Github Actions Workflow #26

### PR DESCRIPTION
**Pull request by murilosandiego**
* Adds CodeCov to Github Actions Workflow and add Codecov badge into Readme. For the Badge link to work, you need to activate the repository on Codecov. I activated the repository in my Codecov account and it is working perfectly, as you can see in the main branch of my repository

* Adds CodeCov to Github Actions Workflow #26

## Pre-launch Checklist

- [x] Eu li o [CONTRIBUTING.md](../CONTRIBUTING.md) e segui as sugestões descritas ali sobre boas práticas de código / I
read [CONTRIBUTING.md](../CONTRIBUTING.md) and followed the suggestions proposed there about writing good code;
- [x] Eu listei pelo menos um issue relacionado à este PR / I listed at least one issue related to this PR;
- [x] Eu adicionei novos testes para cobrir as mudanças que eu fiz neste PR, ou este PR é uma exceção / I added new 
tests that cover the changes made in this PR or this PR is a test-exception;
- [ ] Eu atualizei o [CHANGELOG.md](./../CHANGELOG.md) com as mudanças feitas neste PR / I updated 
[CHANGELOG.md](./../CHANGELOG.md) with the changes made in this PR;
- [x] Eu atualizei/adicionei comentários relevantes nas modificações efetuadas / I updated or added relevant docs in the
modifications I've made;
- [x] Todos os testes previamente existentes e os novos criados por mim estão finalizando com sucesso / All the existing
tests - the old and the new ones - are finishing with success.

### CODE REVIEW

**Review by RaphaelOliveiraMoura — APPROVED** [review]

**Comment by RaphaelOliveiraMoura** [comment]
@murilosandiego The Ci broken at flutter analyze:

image

Two of these points can be resolved with #29 issue

---

And the other point is a method that isn't used yet: 
method `_insertPage` at `lib/application/coordinator/routes_coordinator.dart:110:8`

I think we can do one of this two things to fix the warning:

1) Add a comment to ignore the alert of unused method, like this:

image

2) Or, for now, remove this method

**Comment by murilosandiego** [comment]
Hello, @RaphaelOliveiraMoura . I have made the corrections you suggested.

**Review by RaphaelOliveiraMoura — APPROVED** [review]

**Comment by matuella** [comment]
As mentioned in a recently [created issue](https://github.com/olmps/strict/issues/5), this is indeed a rule that should be changed in the core lint library. I will make the updates to strict first so we don't need to change the `analysis_options` file.

**Comment by matuella** [comment]
First of all, thanks for contributing!

As mentioned in a recently [created issue](https://github.com/olmps/strict/issues/5), this is indeed a rule that should be changed in the core lint library. I will make the updates to strict first so we don't need to change the `analysis_options` file.

**Comment by ggirotto** [comment]
@murilosandiego Thanks for the contribution! While we wait to @matuella to make the adjustments in the lint rules, you can add the coverage tag in [ptBR README](https://github.com/olmps/memo/blob/main/README_ptbr.md) as well

**Comment by RaphaelOliveiraMoura** [comment]
@murilosandiego I think you can undo the changes on `analysis_options.yaml` now, because the lint rules was updated on the `strict` repository

**Comment by murilosandiego** [comment]
I have updated the version of strict and removed the linter rules

**Review by RaphaelOliveiraMoura — APPROVED** [review]

**Review by ggirotto — APPROVED** [review]

**Comment by ggirotto** [comment]
Thanks for the contribution @murilosandiego

**Pull request merged**
