### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by danieldecasttro**
*Faça aqui uma breve descrição das alterações que esse PR faz e o porquê / Describe the changes proposed in this PR and
their motivation:*

The index of sections on [README.md](https://github.com/olmps/memo#readme) is "Setup: how **_the_** configure your local project;" but should be "Setup: how **_to_** configure your local project;".

*Liste pelo menos um issue relacionado à este PR. / List at least one open issue related to this PR:*

## Pre-launch Checklist

- [x] Eu li o [CONTRIBUTING.md](../CONTRIBUTING.md) e segui as sugestões descritas ali sobre boas práticas de código / I
read [CONTRIBUTING.md](../CONTRIBUTING.md) and followed the suggestions proposed there about writing good code;
- [ ] Eu listei pelo menos um issue relacionado à este PR / I listed at least one issue related to this PR;
- [ ] Eu adicionei novos testes para cobrir as mudanças que eu fiz neste PR, ou este PR é uma exceção / I added new 
tests that cover the changes made in this PR or this PR is a test-exception;
- [ ] Eu atualizei o [CHANGELOG.md](./../CHANGELOG.md) com as mudanças feitas neste PR / I updated 
[CHANGELOG.md](./../CHANGELOG.md) with the changes made in this PR;
- [ ] Eu atualizei/adicionei comentários relevantes nas modificações efetuadas / I updated or added relevant docs in the
modifications I've made;
- [ ] Todos os testes previamente existentes e os novos criados por mim estão finalizando com sucesso / All the existing
tests - the old and the new ones - are finishing with success.

### CODE REVIEW

**Comment by ggirotto** [comment]
Hey @danieldecasttro, we are currently investigating an issue with our CI `pull-request` workflow, that's why we haven't approved and merged your PR yet.

**Comment by danieldecasttro** [comment]
> Hey @danieldecasttro, we are currently investigating an issue with our CI `pull-request` workflow, that's why we haven't approved and merged your PR yet.

No problem! I saw the I saw the PR failing checks and realize it.

**Comment by ggirotto** [comment]
Hey @danieldecasttro, we've identified the issue with our `pull-request` workflow and we're working in a solution to it. This issue will proceed in https://github.com/olmps/memo/issues/154. Once we resolve it, I'll approve and merge your PR

**Comment by ggirotto** [comment]
Hey @danieldecasttro. https://github.com/olmps/memo/pull/156 was merged on main. You may now rebase with the main branch in the PR should be good to go

**Pull request merged**
